[package]
name = "practicaCabra"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
  "bevy_winit",        
  "bevy_render",        
  "bevy_sprite",        
  "bevy_core_pipeline", 
  "bevy_text",          
  "bevy_ui",            
  "png",                
  "x11"                 
] }



